version: '2'

services:
  erbi_nlp:
    image: erbi_nlp
    build: ./src/erbi_nlp
    command: ros2 run erbi_nlp nlp_alive_pub
  erbi_nlp2:
    image: erbi_nlp
    build: ./src/erbi_nlp
    command: ros2 run erbi_nlp nlp_alive_sub
    depends_on:
      - erbi_nlp