version: '2'

services:
  erbi_cv:
    image: erbi_cv:latest
    build: ./src/erbi_cv
    #command: ros2 run demo_nodes_cpp talker
  talker:
    image: osrf/ros:humble-desktop
    command: ros2 run demo_nodes_cpp talker
  listener:
    image: osrf/ros:humble-desktop
    command: ros2 run demo_nodes_cpp listener
    depends_on:
      - talker